name: Desplegar sitio estático en GitHub Pages

on:
  # Se ejecuta cada vez que haces un cambio (push) a la rama 'main'
  push:
    branches: ["main"]

  # Te permite ejecutarlo manualmente desde la pestaña 'Actions' si es necesario
  workflow_dispatch:

# Permisos para que GITHUB_TOKEN pueda desplegar en Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite una sola implementación concurrente (cancela las anteriores si hay nuevas)
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Obtener código)
        uses: actions/checkout@v4

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Subir artefacto (Tus archivos HTML, CSS, JS)
        uses: actions/upload-pages-artifact@v3
        with:
          # El '.' significa que subirá todo lo que esté en la raíz del repositorio
          path: '.'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4